# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GeoIP' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'Alamofire'
  pod 'AlamofireObjectMapper'
  pod 'SwiftLint'

  target 'GeoIPTests' do
  inherit! :search_paths
  	pod 'Alamofire'
  	pod 'AlamofireObjectMapper'
  	pod 'SwiftLint'
  end

end
